### ISSUE TITLE
How to retrieve the deposition from the create action

### ISSUE THREAD

**Issue by FriederikeHanssen** [popperized/zenodo#7]
Hi! I am trying to upload a data set to Zenodo using this action. So far I am running the create action first and the upload one. How can I retrieve the deposition ID from the create action and feed it into the upload one?

```
     - name: Download metadata file for Zenodo
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            assets/zenodo.json
          sparse-checkout-cone-mode: false

      - name: Create new Zenodo entry
        uses: popperized/zenodo/create@master
        env:
          ZENODO_METADATA_PATH: assets/zenodo.json
        with:
          secrets: ${{ secrets.ZENODO_API_TOKEN }}

      - name: Upload file to Zenodo
        uses: popperized/zenodo/upload@master
        env:
          ZENODO_DEPOSIT_ID:  #TODO get the dposit ID from the previous step
          ZENODO_UPLOAD_PATH: ./variant_calling_v$pipeline_version
        with:
          secrets: ${{ secrets.ZENODO_API_TOKEN }}
```
